__default__ :
    jobname      : "{rule}"
    output        : "logs/slurm_{rule}/%j.out"
    ntasks        : 1
    cpus-per-task : 1
    mem           : "4G"
    time          : "00-00:20:00"
    account       : "ft413468"
    partition     : "normal,normal,test,parallell"

trim:
    time          : "3:00:00"
    mem           : "8G"

align:
    time          : "3-00:00:00"
    mem           :  "16G"
    cpus-per-task : 4

methylation_extractor:
    time          : "04:00:00"
    mem           : "16G"
    cpu           : "9"

